{{- if .Values.installOperator }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.operatorNamespace }}
---
apiVersion: helm.sh/v1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: {{ .Values.operatorNamespace }}
spec:
  interval: 10m
  url: https://charts.external-secrets.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: {{ .Values.operatorNamespace }}
spec:
  interval: 10m
  chart:
    spec:
      chart: external-secrets
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: {{ .Values.operatorNamespace }}
      version: "0.9.9"
  values:
    installCRDs: true
{{- end }}
