{{- if .Values.secretStore.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name }}
  namespace: {{ .Values.secretStore.namespace }}
spec:
  provider:
    github:
      # Reference to a secret containing your GitHub PAT
      # This secret will be created separately (either manually or via another ExternalSecret)
      auth:
        secretRef:
          secretAccessKey:
            name: github-pat-bootstrap
            key: token
      # Your GitHub repository (owner/repo format)
      repository: red512/vimex
{{- end }}
