---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-key
  namespace: {{ .Values.namespace.name }}
spec:
  encryptedData:
    API-KEY: AgCy/9OdNmfaupgAasO4T39jb/85jdv/eCEaLsukg3oZNdNQaaIAvuQPUQREZYOvS9S8AujgYzPzl9k5XEqDcgo1ve1peD1IX2UYq9h30u/Z4htT4HuqeAhicZnLpdvHtEh2Ju8jKdhfTD1gF11XpqccrhXwClsP4QoaTXCf+JJo7r7Jiakjkiawx+FEs/0vkdBAraiSkOI6ZohnzZV2AMgMn/NiEXpqpF0eufMBVr7Xoaercjf/1Ljsq9prNXD0rLQurGDFvcqEzx2oX2j5ZMxKtGd7NxZ84b1WrGOb684nzsLeWxj/i0VW6mNwXHZHgcwA8rkZjhuVhJXK5byjg728pqQCLiHxkd0pjmGt7TxzKd5eGG++9Kx5IKOzJk02J8euQOWHLO4l9cbg0MhB8WXoXzxl4SDRWtye8O/u6SteSLYRkaBFJUle4X3WAR2zL21jqoLkONQayZ3x3w2vN2duAYvBp4H5b7mmkaitIUf37TCPJEunh16Ty6p1zoRB5LmlOCuugrL8ekx9opjueHKuZmHuOgWjJDR+nBXlw+OrtLISsAN/dGZdLtyV6n5b7mhs1F2jEbVfkSPcSAz1Ebl0pwUSJmQiWPpt2r4tyb83D4YngMmnN9ddrPUqAUrkpfJks23SoTaCT9wL7vtcpzBX0NHUbYpCacBPq6EqyqnoRa/+EBFpFW3RXQ/K1wpzmKooY5kwRCmGXODcLNVNrlfkAuoVTCt3uC/o2WfjOIZZcg==
  template:
    metadata:
      name: api-key
      namespace: {{ .Values.namespace.name }}
